name: coletanea_digital
description: "Coletânea Digital - Aplicação mobile-first e offline-first para consumo de louvores e materiais"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.2.1

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # PDF Reader
  pdfrx: ^2.2.24

  # Audio Player
  just_audio: ^0.9.43

  # Routing
  go_router: ^17.1.0

  # Network
  dio: ^5.9.1
  connectivity_plus: ^6.1.1

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # File System
  path_provider: ^2.1.1
  
  # UUID
  uuid: ^4.3.3

  # Launch URLs (YouTube, etc.)
  url_launcher: ^6.3.1

  # Ícone do YouTube (brand)
  font_awesome_flutter: ^10.7.0
  
  # Google Fonts
  google_fonts: ^6.2.1
  
  # SVG Support
  flutter_svg: ^2.0.10+1
  just_audio_background: ^0.0.1-beta.17
  archive: ^4.0.9
  flutter_client_sse: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/LOGO_BRANCO.svg
    - assets/logo/LOGO_COLORIDO.svg
    - assets/logo/LOGO_COLORIDO_INLINE_GOLD_LIGHT.svg
    - assets/logo/LOGO_PRETO.svg
    - assets/logo/LOGO_ONLY_GOLD_DARK.svg
